### ISSUE TITLE
issue to port a commit to 76

### ISSUE THREAD

**Issue by sdevissc** [cp3-llbb/Framework#119]
Hi, 

Just a small issue which I don't get when rebasing: I want to port the commit https://github.com/cp3-llbb/Framework/pull/117/commits to 76, so I do 

git fetch upstream
git checkout CMSSW_7_6_3p
git rebase -i CMSSW_7_4_12p

which gives me 

error: could not apply c2dd009... Add PU systematics

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not apply c2dd009... Add PU systematics

Any about either what I do wrong (highly probable) or what is going on?

Thanks

Simon

**Comment by sdevissc** [comment]
Ok, I probably where the issue is, I close this.

**Comment by sdevissc** [comment]
I re-open: now I do

git fetch origin (to have access to the branch "AddZcriterin" in my github)

then, checkout the CMSSW_7_6_3p branch

git fetch upstream
git checkout CMSSW_7_6_3p

and then

git rebase -i AddZcriterin

and again:

error: could not apply c2dd009... Add PU systematics

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not apply c2dd009... Add PU systematics

Any idea? Thanks!

**Comment by blinkseb** [comment]
You should not used rebase, since it'll basically try to merge one branch into another, and the two branches are not compatible. This is what is usually do.

 1) I note the SHA of the commit I want to backport. In your case, it's https://github.com/cp3-llbb/Framework/commit/c1afab34d2750e8de8298175ed980813eb263256, so `c1afab34d2750e8de8298175ed980813eb263256`
 2) I create a new branch starting from the branch I want to merge to: `git checkout -b AddZcriterin_76 upstream/CMSSW_7_6_3p`
 3) I cherry-pick the commit(s) I want in this new branch: `git cherry-pick c1afab34d2750e8de8298175ed980813eb263256`
 4) Then push the branch in my fork and create a PR: `git push origin AddZcriterin_76`

Tell me if it works for you

**Comment by sdevissc** [comment]
Great, it works! Thanks a bunch!
