### ISSUE TITLE
Tagging new releases

### ISSUE THREAD

**Issue by blinkseb** [cp3-llbb/Framework#88]
I propose to tags two new releases for upcoming production:

For branch `CMSSW_7_4_10m` (most probably a legacy tag)

```
v0.2.0+7410
```

For branch `CMSSW_7_4_12p`

```
v1.0.0+7415
```

**Comment by OlivierBondu** [comment]
why the major release for 7.4.12 ? 

no other issues on my end

**Comment by OlivierBondu** [comment]
actually another minor comment: the new triggering electron MVA is out [since 5:40 pm](https://hypernews.cern.ch/HyperNews/CMS/get/egamma/1638.html), should this be put in ?
(we only store/use cut-based ID on the HH side for the moment, so this can wait on our side we do not care)

**Comment by blinkseb** [comment]
The major bump is because we broke the API in 7.4.12+ with #68.

Concerning the MVA id, I can easily do a PR later or tomorrow. We also only use cut based for now, but it's definitively a thing to add in a near future.

**Comment by swertz** [comment]
It seems electron isolation is not included in the mvaID (contrary to cutID): this makes the situation a bit more symmetric with muons (not completely: there are only 2 "recommended" WPs for mvaID instead of 3 muonIDs... Also, do you guys know how it's going to work with SF? Will there be SF provided for these two recommended working points, or is the WP analysis-dependent?). 
This means we have to define some isolation working points. For muons I think the two values I've run into are 0.2 (loose) and 0.12 (tight), but is there anything close to recommended values for electrons? The iso cuts in the cutID are quite strong (up to 0.03 for tightID in the barrel)...

**Comment by OlivierBondu** [comment]
for the SF, I guess we'll have more insight by the end of the week, since the EPR discussions (are likely to) affect the POG personpower to deliver these...

In principle, the best you can do is analysis dependent since it depends on the topology of the event / the backgrounds you are fighting against. Bref, I'd keep them all and decide when it converges :smile:

**Comment by OlivierBondu** [comment]
The [night tests](http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Olivier+Bondu&refresh=300&table=Mains&p=1&records=100&activemenu=2&pattern=&task=&from=&till=&timerange=lastWeek) were successful, no objection to go on with tagging on my end

As for the analyzers, should we agree on something like `2015-10-09.0` for tagging (as discussed with @blinkseb) ? the index following the date being for keeping track of possible last-minute bug fixes

**Comment by blinkseb** [comment]
Tags and releases created!
